### PR TITLE
Set up continuous integration testing via Travis-CI.

### PR DESCRIPTION
**Pull request by peti**
The build script is generated by https://github.com/haskell-CI/haskell-ci. I have not enabled doctest and hlint verification yet, but I figure we could. Check out the current results at https://travis-ci.org/peti/stylish-cabal.

### CODE REVIEW

**Comment by pikajude** [comment]
Wow, this looks great! I'm worried about the GHC < 8.2 test failures, though. Looks like cabal can't fulfill the Cabal == 2.0.* version constraint; do you know why that would be? I see `Cabal-2.0.1.1, Cabal-2.0.1.0, Cabal-2.0.0.2` in the "rejected" list. Is that actually an issue with the constraints on this package? (Forgive me, I haven't actually used cabal's dependency solver in a LONG time since I've been fully immersed in the Nix world)

**Comment by pikajude** [comment]
Have manually merged this to the `travis_ci` branch so I can resolve the dependencies issues before merging to master.

**Comment by peti** [comment]
Those failures should go away when the build script is generated with `make-travis-yml --no-installed`. Testing that the project can be built with "installed constraints" makes no sense for a build that needs a very new version of Cabal. In such a case, the installed version is clearly not good enough on older platforms.

**Comment by pikajude** [comment]
I ended up figuring out *exactly* what the installed constraints build does yesterday but I'm not saying how long it took.

**Pull request closed without merging**
